workflows:
  ios-release:
    name: iOS Release (TestFlight)
    max_build_duration: 60
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: Journaly_ASC

    environment:
      groups:
        - journaly_env
      vars:
        BUNDLE_ID: "com.journaly.app"
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
      node: 22.0.0
      xcode: latest

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Install Node dependencies
        script: npm ci

      - name: Build web app
        script: npm run build

      - name: Sync iOS platform
        script: npx cap sync ios

      - name: Update iOS deployment target
        script: |
          cd ios/App
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*/IPHONEOS_DEPLOYMENT_TARGET = 14.0/g' App.xcodeproj/project.pbxproj

      - name: Configure iOS permissions
        script: |
          /usr/libexec/PlistBuddy -c "Add :NSMicrophoneUsageDescription string 'Journaly needs access to your microphone to record voice journal entries'" ios/App/App/Info.plist || true

      - name: Initialize keychain
        script: keychain initialize

      - name: Fetch signing files from App Store Connect
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create

      - name: Add certificates to keychain
        script: keychain add-certificates

      - name: Apply provisioning profiles to Xcode project
        script: xcode-project use-profiles

      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - ios/App/App/Info.plist

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Beta Testers
