workflows:
  ios-release:
    name: iOS Release (TestFlight)
    max_build_duration: 60
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: Journaly_ASC

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.journaly.app
      vars:
        # Ces variables seront configurées dans Codemagic Dashboard
        VITE_SUPABASE_URL: $VITE_SUPABASE_URL
        VITE_SUPABASE_ANON_KEY: $VITE_SUPABASE_ANON_KEY
        VITE_GEMINI_API_KEY: $VITE_GEMINI_API_KEY
      node: 18.17.0
      xcode: latest
      cocoapods: default

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Install Node dependencies
        script: |
          npm ci

      - name: Build web app
        script: |
          npm run build

      - name: Add iOS platform
        script: |
          npx cap add ios || true
          npx cap sync ios

      - name: Update iOS project settings
        script: |
          # Set iOS deployment target
          cd ios/App
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*/IPHONEOS_DEPLOYMENT_TARGET = 14.0/g' App.xcodeproj/project.pbxproj

      - name: Configure iOS permissions
        script: |
          # Add microphone permission to Info.plist
          /usr/libexec/PlistBuddy -c "Add :NSMicrophoneUsageDescription string 'Journaly needs access to your microphone to record voice journal entries'" ios/App/App/Info.plist || true

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install

      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "com.journaly.app" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles

      - name: Build iOS app
        script: |
          cd ios/App
          xcode-project build-ipa \
            --workspace App.xcworkspace \
            --scheme App \
            --archive-flags="-destination 'generic/platform=iOS'"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - ios/App/App/Info.plist

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Beta Testers
